# Generated by Django 5.2.6 on 2025-10-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_course_purchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_purchase",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=1400,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
